name: duckdb-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.11
  - duckdb>=0.9.2
  - pandas>=2.0.0
  - numpy>=1.25
  - pyarrow>=13.0.0
  - jupyter
  - ipykernel
  - matplotlib
  - seaborn
  - requests
  - tqdm
  - pip
  - pip:
      - sqlalchemy
      - polars
      - rich
